### ISSUE TITLE
make tensorflow optional

### ISSUE THREAD

**Issue by jschueller** [anthony-nouy/tensap#2]
tensorflow is an hard requiremment for various specific things:
```
../tensap/tensap/tensor_algebra/tensors/full_tensor.py:24:from tensorflow.python.ops.gen_linalg_ops import qr
../tensap/tensap/tensor_algebra/tools/truncator.py:23:from tensorflow import Tensor as tf_Tensor
../tensap/tensap/approximation/learning/loss_functions.py:23:from tensorflow import reduce_mean
```

hopefully it could become completely optional if we could rely on scipy et al, eg from full_tensor.py we have:
```
from tensorflow.python.ops.gen_linalg_ops import qr
...
# tensor.data, r_matrix = np.linalg.qr(tensor.data)
q_tf, r_tf = qr(tensor.data, full_matrices=False)
```

maybe it could become optional with this kind of pattern:
```
try:
    from tensorflow.python.ops.gen_linalg_ops import qr 
    q_tf, r_tf = qr(tensor.data, full_matrices=False)
except ImportError:
   q_tf, r_tf = np.linalg.qr(tensor.data)
```

**Comment by jschueller** [comment]
Another motivation for this is that on conda-forge they only have tensorflow 1.13, so tutorials cannot be run there, I guess we rely on tf>=2.0 or something.
```
tensor.data, r_matrix = q_tf.numpy(), r_tf.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy
```

**Comment by egrelier** [comment]
The package tensorflow will be made optional in the next commit, except when using the class LinearModelLearningCustomLoss and running the tutorial tutorial_tensor_learning_digits_recognition.py, that both require it.

**Comment by jschueller** [comment]
can you push the commits ?

**Comment by egrelier** [comment]
The commit will be pushed once it is ready in a few minutes!

**Comment by jschueller** [comment]
ok, sorry

**Comment by egrelier** [comment]
No problem, the commit is now pushed.
