### ISSUE TITLE
version 1.2 on pypi

### ISSUE THREAD

**Issue by jschueller** [anthony-nouy/tensap#25]
hi @anthony-nouy, the latest version on pypi is still 1.1 and not 1.2 that has the latest fixes

**Comment by anthony-nouy** [comment]
Hello Julien,
Could you tell how to have the new new version 1.2 on pypi ?

**Comment by jschueller** [comment]
Hi Anthony, its done, just a matter of:
```
python3 setup.py sdist
twine upload dist/tensap-1.2.tar.gz
```
