### ISSUE TITLE
Method FullTensor.sparse() is not working

### ISSUE THREAD

**Issue by MLasserre** [anthony-nouy/tensap#28]
Hi,
I think there is a bug in the FullTensor.sparse() method.
It only works when there are no zeros in the FullTensor.
This MWE will raise en error:

```
import tensap
import numpy as np

tensor = tensap.FullTensor(np.random.choice([0,1], size=24, p=[2/3, 1/3]).reshape((3,4,2)))
tensor.sparse()
```

I guess that the line 167 of full_tensor.py should be something like:
`tensap.SparseTensor(dat[ind], indices, tensor.shape)`
in order to only keep non-zero values.

**Comment by jschueller** [comment]
care to send a patch ? we'll see if tutorials still pass CI with this

**Comment by MLasserre** [comment]
diff --git a/tensap/tensor_algebra/tensors/full_tensor.py b/tensap/tensor_algebra/tensors/full_tensor.py
index b234586..5d2ab65 100644
--- a/tensap/tensor_algebra/tensors/full_tensor.py
+++ b/tensap/tensor_algebra/tensors/full_tensor.py
@@ -164,7 +164,7 @@ class FullTensor:
         dat = np.reshape(self.data, -1, order='F')
         ind = np.nonzero(dat)[0]
         indices = tensap.MultiIndices.ind2sub(self.shape, ind)
-        return tensap.SparseTensor(dat, indices, self.shape)
+        return tensap.SparseTensor(dat[ind], indices, self.shape)
 
     def __repr__(self):
         return ('<{} FullTensor:{n}' +

**Comment by MLasserre** [comment]
No, I don't mind.
I have created it but I don't know how to share it since github doesn't support these kind of files.
Should I send it here in plain text ?

**Comment by jschueller** [comment]
I meant send a pull request

**Comment by jschueller** [comment]
can be closed @anthony-nouy

**Comment by anthony-nouy** [comment]
Thank you Jean-Bernard !

**Comment by jschueller** [comment]
:]
