### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by jschueller** [anthony-nouy/tensap#33]
the 1.2 version in pip/conda is unusable because of numpy errors (fixed on master) on recent versions:
`AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?`

are there plans to draft a new release ?
(bump the version first at https://github.com/anthony-nouy/tensap/blob/master/tensap/__init__.py#L21)

**Comment by jschueller** [comment]
first bump the version in __init__.py then tag the new version on github

then to publish it on pypi:
```
python3 setup.py sdist
twine upload dist/tensap-1.2.tar.gz
```

**Comment by jschueller** [comment]
actually "numpy float" is still ok to designate the type associated to a return value from a numpy array operation as np.float64 still exists
other plain python real numbers are called "float"
in the other hand "scalar" is not used in the Python world, so I suggest to go back to "float"
either we make the distinction between "numpy float" and regular "float", or we just call everything "float" as the distinction is probably not so important

**Comment by anthony-nouy** [comment]
If the entries of a tensor are float the result is float. But if you define a tensor with integer entries (eg numpy.int64) it returns a numpy.int64.  ... Then i used scalar since the command numpy.isscalar(output) returns True in any case. But i would be ok for using regular float. What do you think ?

**Comment by jschueller** [comment]
oh, I did not think of integers, then I guess scalar is fine then

**Comment by anthony-nouy** [comment]
ok !

**Comment by jschueller** [comment]
you didnt push the tag ?

**Comment by anthony-nouy** [comment]
I am checking a few things before. I have to commit some bug fixes.

**Comment by anthony-nouy** [comment]
It is ready to be pushed on pypi but i am not allowed to upload the project tensap on pypi.
Either you do it Julien, or you give me the rights.
Thanks

**Comment by jschueller** [comment]
done

**Comment by anthony-nouy** [comment]
Hi Julien,
I received your invitation for tensap on pypi but when i follow the link, i obtain"jeton invalide: pas de jeton fourni".
I realized that the v1.3 contained again several formatting issues and conda build failed. I corrected everything and will tag a v1.4.
Thanks

**Comment by anthony-nouy** [comment]
Seems i was too late to use the link, sorry.

**Comment by jschueller** [comment]
no need for a new release if its only a formatting issue ; this wont affect users

**Comment by anthony-nouy** [comment]
There was also important bug fixes in the basic tensor algebra, for cases that are not that usual but i prefer skipping the v1.3
